EntryDesignConcept/Controllers/EntryController.cs
using EntryDesignConcept.AppContext;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EntryDesignConcept.Models;

namespace EntryDesignConcept.Controllers
{
    public class EntryController : Controller
    {
        private ActivityContext db = new ActivityContext();
        //
        // GET: /Entry/
        public ActionResult Index()
        {
            ActivitiesViewModel actv = new ActivitiesViewModel();
            actv.PositionID = 2;
            return View(actv);
        }

        
	}
}

EntryDesignConcept/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TES Design Concept</title>

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <link href="~/Content/metro-bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/calendar-2.4/fullcalendar.css" rel="stylesheet" />
    <link href="~/Content/jquery-ui.min.css" rel="stylesheet" />
    <script src="~/calendar-2.4/moment.min.js"></script>
    <script src="~/calendar-2.4/jquery.min.js"></script>
    <script src="~/calendar-2.4/fullcalendar.min.js"></script>
    <link href="~/fonts/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <style>
        body {
            padding-top: 0;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-default" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Time Entry System", "Index", "Entry", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">        
                    <li><a href="/Activity">Activity</a></li>
                    <li><a href="/Billability">Billability</a></li>                   
                    <li><a href="/Organization">Organization</a></li>
                    <li><a href="/Position">Position</a></li>
                    <li><a href="/SalesOrder">Sales Order</a></li>  
                    <li><a href="/Team">Team</a></li>    
                    <li><a href="/User">User</a></li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        @RenderBody()
    </div>


    <script src="~/Scripts/bootstrap.min.js"></script>
   
    @RenderSection("scripts", false);
</body>
</html>